version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB=taskdb
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
